apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-web
  namespace: argocd
  finalizers:
  - finalizer.argocd.kevin.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ci/my-values.yaml
    path: nginx-webserver/nginx-web15.1.0
    repoURL: https://github.com/brayanlee/k8s-repo-manifest.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
